"""nullable storage path

Revision ID: 01a97d1bec99
Revises: e09bc37f5697
Create Date: 2026-09-08 10:55:30.518662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01a97d1bec99'
down_revision: Union[str, None] = 'e09bc37f5697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_metadata', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image_metadata', 'storage_path',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
