"""add agent_traces success and error_message columns

Revision ID: 03336391c4b5
Revises: 3563f3c7500e
Create Date: 2026-09-08 13:49:46.224182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03336391c4b5'
down_revision: Union[str, None] = '3563f3c7500e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_traces', sa.Column('success', sa.Boolean(), nullable=False))
    op.add_column('agent_traces', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_traces', 'error_message')
    op.drop_column('agent_traces', 'success')
    # ### end Alembic commands ###
