"""add users table and user_sessions.user_id

Revision ID: 9429c5e5b5cf
Revises: cd58b9729456
Create Date: 2026-09-11 20:09:30.920253

Release-hardening follow-up: closes "anonymous session ID alone grants
access" by giving each UserSession an owner. user_sessions.user_id is
NOT NULL with no default -- this assumes no pre-existing anonymous
session data needs preserving across the change, true for every
environment this project actually runs in (local Docker, wiped with
`docker compose down -v`). A real deployment with live anonymous
session data would need a backfill step before this migration, which is
deliberately not built here (see docs/persistence.md's Security
section).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9429c5e5b5cf'
down_revision: Union[str, None] = 'cd58b9729456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('user_sessions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=True)
    op.create_foreign_key(
        'fk_user_sessions_user_id_users', 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_sessions_user_id_users', 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_column('user_sessions', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
