"""phase 8: routine analysis and comparison records, chat session linkage columns

Revision ID: cd58b9729456
Revises: 03336391c4b5
Create Date: 2026-09-08 17:15:55.745136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd58b9729456'
down_revision: Union[str, None] = '03336391c4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_records_session_id'), 'comparison_records', ['session_id'], unique=False)
    op.create_table('routine_analysis_records',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_analysis_records_session_id'), 'routine_analysis_records', ['session_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('skin_analysis_id', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('product_id', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('routine_analysis_id', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('comparison_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'comparison_records', ['comparison_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chat_sessions', 'routine_analysis_records', ['routine_analysis_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chat_sessions', 'skin_analyses', ['skin_analysis_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chat_sessions', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'comparison_id')
    op.drop_column('chat_sessions', 'routine_analysis_id')
    op.drop_column('chat_sessions', 'product_id')
    op.drop_column('chat_sessions', 'skin_analysis_id')
    op.drop_index(op.f('ix_routine_analysis_records_session_id'), table_name='routine_analysis_records')
    op.drop_table('routine_analysis_records')
    op.drop_index(op.f('ix_comparison_records_session_id'), table_name='comparison_records')
    op.drop_table('comparison_records')
    # ### end Alembic commands ###
